# Deck corporativo BPM Tech. Copy tomado de src/data/copy.json («diseño final», 15-sep-2026)
# y del BPM Tech Design System v1.0 (aprobado el 17-sep-2026). Sin métricas, clientes ni
# resultados inventados. Las capturas son reales, con datos de demo.
DECK = {
    "meta": {
        "title": "BPM Tech — Presentación corporativa 2026",
        "subject": "Software y webs que encajan en tu negocio",
        "author": "BPM Tech",
        "comments": "Contenido corporativo basado en el copy definitivo de la web (septiembre 2026) y en proyectos reales con capturas de demo.",
        "footer_label": "BPM TECH · PRESENTACIÓN CORPORATIVA",
    },
    "slides": [
        {
            "layout": "cover",
            "eyebrow": "PRESENTACIÓN CORPORATIVA · 2026",
            "client": "SOFTWARE Y WEBS A MEDIDA PARA PYMES",
            "title": "SOFTWARE Y WEBS QUE ENCAJAN EN TU NEGOCIO",
            "subtitle": "Construimos software, automatizaciones y webs a medida para pymes y startups. Hablas directamente con quien entiende el problema, toma las decisiones y desarrolla la solución.",
            "status": "PROYECTOS · SERVICIOS · MÉTODO",
            "confidentiality": "DOCUMENTO CORPORATIVO",
            "date": "18 SEP 2026",
        },
        {
            "layout": "editorial",
            "eyebrow": "01 · PUNTO DE PARTIDA",
            "title": "DEJA DE ADAPTAR TU NEGOCIO A HOJAS DE CÁLCULO",
            "body": "Procesos manuales, software genérico, herramientas que no encajan, parches. Construimos software, automatizaciones y webs a medida para pymes y startups: menos intermediarios, menos vueltas y más velocidad.",
            "aside_label": "PRINCIPIO",
            "aside": "Hablas directamente con quien entiende el problema, toma las decisiones y desarrolla la solución.",
        },
        {
            "layout": "pillars",
            "eyebrow": "02 · SERVICIOS",
            "title": "¿QUÉ TE ESTÁ FRENANDO?",
            "lead": "No necesitas saber qué tecnología necesitas. Cuéntanos qué no está funcionando como debería y encontraremos la forma más sencilla de resolverlo.",
            "items": [
                {
                    "index": "01",
                    "title": "Ordenar la operativa",
                    "body": "Tu gestión depende de hojas de cálculo, mensajes y herramientas que no se hablan entre sí. Una aplicación hecha alrededor de cómo trabaja tu negocio: centralizamos información y eliminamos pasos manuales.",
                    "signal": "ALMACÉN · RESERVAS · CRM · PANELES INTERNOS",
                },
                {
                    "index": "02",
                    "title": "Conectar y automatizar",
                    "body": "Copias datos de un sitio a otro y repites tareas que deberían ocurrir solas. Automatizamos el proceso, conectamos tus sistemas y usamos IA cuando realmente aporta.",
                    "signal": "CONECTAR UN CRM · PROCESAR DOCUMENTOS · SINCRONIZAR",
                },
                {
                    "index": "03",
                    "title": "Crear o mejorar una web",
                    "body": "Tienes una idea, un producto o una web que todavía no representa lo que quieres construir. Desde una web que explique mejor tu negocio hasta un MVP o producto digital completo.",
                    "signal": "WEBS CORPORATIVAS · MVP · SAAS · PORTALES",
                },
            ],
        },
        {
            "layout": "process",
            "eyebrow": "03 · MÉTODO",
            "title": "DEL PROBLEMA A UNA SOLUCIÓN QUE PUEDAS USAR",
            "lead": "Sin cajas negras ni meses esperando para ver resultados. Cada fase termina con algo que puedes revisar.",
            "steps": [
                {"index": "1.0", "title": "Entendemos", "body": "↳ Problema y siguiente paso"},
                {"index": "2.0", "title": "Diseñamos", "body": "↳ Alcance por escrito"},
                {"index": "3.0", "title": "Construimos", "body": "↳ Versiones que puedes probar"},
                {"index": "4.0", "title": "Lanzamos", "body": "↳ Solución lista para usar"},
                {"index": "5.0", "title": "Evolucionamos", "body": "↳ Continuidad acordada"},
            ],
            "result_label": "PRINCIPIO",
            "result": "Las decisiones importantes quedan claras antes de seguir avanzando.",
        },
        {
            "layout": "section",
            "eyebrow": "04 · TRABAJO RECIENTE",
            "index": "04",
            "title": "PROBLEMAS REALES. SOFTWARE HECHO PARA RESOLVERLOS.",
            "subtitle": "Sectores distintos, una misma forma de trabajar: entender primero el problema y construir después la herramienta que encaja.",
            "signal": "PÁDEL · ALMACÉN · EVENTO · RADIO · ASISTENTE DE IA",
        },
        {
            "layout": "product_showcase",
            "eyebrow": "05 · PADEL CLUB OS · EN PRODUCCIÓN",
            "title": "TODO UN CLUB DE PÁDEL, EN UNA SOLA PLATAFORMA",
            "lead": "Reservas, socios, pagos y competiciones conectados en una misma herramienta. Un panel para el club y un portal para que el jugador reserve desde el móvil sin instalar nada.",
            "image": "screenshots/padel-club-os-reservas.png",
            "caption": "FIG. 01 · PADEL CLUB OS · RESERVAS · DATOS DE DEMO · PADELCLUBOS.COM",
            "points": [
                {"index": "01", "title": "Reservas", "body": "El jugador reserva desde el móvil sin instalar nada."},
                {"index": "02", "title": "Socios y pagos", "body": "Cuotas y cobros conectados en la misma herramienta."},
                {"index": "03", "title": "Competiciones", "body": "Torneos gestionados desde el panel del club."},
                {"index": "04", "title": "Panel del club", "body": "Pistas, cuotas y torneos administrados en un solo sitio."},
            ],
        },
        {
            "layout": "product_showcase",
            "eyebrow": "06 · GESTIÓN DE ALMACÉN · WEB + TERMINAL RF",
            "title": "DEL CONTROL MANUAL A UN ALMACÉN CONECTADO",
            "lead": "Inventario, ubicaciones y movimientos reunidos en una herramienta con permisos por rol, más un terminal RF para operar con escáner o con la cámara del móvil.",
            "image": "screenshots/almacen-movimientos.png",
            "caption": "FIG. 02 · LIBRO DE MOVIMIENTOS · DATOS DE DEMO · NOMBRE DEL PRODUCTO DIFUMINADO",
            "points": [
                {"index": "01", "title": "Productos, ubicaciones y stock", "body": "Recuentos, ajustes y órdenes de entrada y salida."},
                {"index": "02", "title": "Libro de movimientos inmutable", "body": "Anular genera un movimiento compensatorio."},
                {"index": "03", "title": "Permisos por rol", "body": "Cada persona ve justo lo que necesita."},
                {"index": "04", "title": "Terminal RF", "body": "Escáner o cámara del móvil, e informes por ubicación y producto."},
            ],
        },
        {
            "layout": "editorial",
            "eyebrow": "07 · UNA DECISIÓN CONCRETA",
            "title": "EL STOCK NO SE EDITA A MANO.",
            "body": "Es la proyección de un libro de movimientos inmutable. Anular genera un movimiento compensatorio, así que siempre se puede reconstruir qué pasó y cuándo.",
            "aside_label": "LA MISMA REGLA",
            "aside": "Sirve para cualquier inventario, caja o registro que hoy se corrija a mano.",
        },
        {
            "layout": "pillars",
            "eyebrow": "08 · SOMOS AI-FIRST",
            "title": "SOMOS AI-FIRST. EL CRITERIO SIGUE SIENDO HUMANO.",
            "lead": "La IA multiplicó la capacidad de un estudio pequeño. Lo que no cambió es quién entiende el problema, toma las decisiones y responde por lo que se entrega.",
            "dark": True,
            "items": [
                {
                    "index": "01",
                    "title": "La IA acelera. El criterio decide.",
                    "body": "Desarrollo, pruebas, documentación y análisis avanzan mucho más rápido. Qué se construye, cómo se estructura y qué se descarta sigue siendo una decisión de producto y de ingeniería.",
                    "signal": "MENOS INTERMEDIARIOS",
                },
                {
                    "index": "02",
                    "title": "Hablas con quien construye",
                    "body": "No hay una cadena de comercial, project manager, analista y desarrollador entre tu problema y la solución. La misma persona participa en las decisiones y en la construcción.",
                    "signal": "MÁS PRODUCTO",
                },
                {
                    "index": "03",
                    "title": "Para resolver, no para complicar",
                    "body": "Si algo puede resolverse con una regla sencilla, no necesita IA. Si existe una herramienta que ya hace bien lo que necesitas, tampoco hace falta reinventarla.",
                    "signal": "CONSTRUIMOS CUANDO APORTA",
                },
            ],
        },
        {
            "layout": "stack",
            "eyebrow": "09 · HERRAMIENTAS",
            "title": "HERRAMIENTAS CON LAS QUE CONSTRUIMOS",
            "lead": "Construimos cuando hacerlo aporta una ventaja real. Si existe una herramienta que ya hace bien lo que necesitas, no hace falta reinventarla.",
            "groups": [
                {"label": "PRODUCTO WEB", "items": ["Next.js", "React"]},
                {"label": "DATOS", "items": ["Supabase"]},
                {"label": "AUTOMATIZACIÓN E IA", "items": ["Python", "Anthropic", "OpenAI"]},
                {"label": "INFRAESTRUCTURA", "items": ["AWS"]},
            ],
            "note": "EL STACK FINAL DEPENDE DEL PROBLEMA, LAS RESTRICCIONES Y EL SISTEMA EXISTENTE",
        },
        {
            "layout": "editorial",
            "eyebrow": "10 · SOBRE BPM TECH",
            "title": "QUIEN DECIDE, CONSTRUYE.",
            "body": "BPM Tech es un estudio de software con base en Valencia. Aquí no explicas tu problema a una persona para que se lo traduzca a otra y termine construyéndolo una tercera: hablas directamente con quien entiende la necesidad, diseña la solución y la desarrolla.",
            "aside_label": "ALBERTO BORT",
            "aside": "Dirección de proyectos y tecnología. Valencia, España. Presencial y en remoto. Primera conversación de 30 minutos por videollamada.",
        },
        {
            "layout": "next_steps",
            "eyebrow": "11 · SIGUIENTES PASOS",
            "title": "¿QUÉ PASA DESPUÉS?",
            "lead": "No necesitas llegar con un proyecto definido. Cuéntanos cómo trabajas hoy, qué te está dando problemas o qué idea quieres poner en marcha.",
            "steps": [
                {"index": "01", "action": "Cuéntanos tu situación", "body": "Revisamos tu situación y hablamos contigo para entenderla.", "timing": "PRIMERA CONVERSACIÓN"},
                {"index": "02", "action": "Una llamada de 30 minutos", "body": "Te explicamos cómo lo resolveríamos y qué tendría sentido hacer primero. Sin compromiso.", "timing": "VIDEOLLAMADA · CAL.COM"},
                {"index": "03", "action": "Alcance y presupuesto", "body": "Todo queda por escrito antes de empezar a construir.", "timing": "PROPUESTA"},
            ],
        },
        {
            "layout": "corporate_closing",
            "eyebrow": "12 · CONTACTO",
            "title": "¿QUÉ DEBERÍA FUNCIONAR MEJOR EN TU NEGOCIO?",
            "lead": "Escríbenos a bpmtechstudio@gmail.com o reserva una llamada de 30 minutos en cal.com/bpmtechstudio/30min. Nosotros nos encargamos de convertirlo en el siguiente paso.",
            "cta": "CUÉNTANOS QUÉ NECESITAS RESOLVER",
            "contact": "VALENCIA · ESPAÑA · BPMTECHSTUDIO.COM",
        },
    ],
}
