DECK = {
    "meta": {
        "title": "BPM Tech — Presentación corporativa 2026",
        "subject": "Capacidades, método y proyectos de BPM Tech",
        "author": "BPM Tech",
        "comments": "Contenido corporativo basado en la web y los proyectos reales anonimizados de BPM Tech.",
        "footer_label": "BPM TECH · PRESENTACIÓN CORPORATIVA",
    },
    "slides": [
        {
            "layout": "cover",
            "eyebrow": "PRESENTACIÓN CORPORATIVA · 2026",
            "client": "BPM TECH",
            "title": "TECNOLOGÍA A MEDIDA PARA EMPRESAS",
            "subtitle": "Aplicaciones, automatización e inteligencia artificial aplicada a la operativa real de cada negocio.",
            "status": "CAPACIDADES · MÉTODO · PROYECTOS",
            "confidentiality": "DOCUMENTO CORPORATIVO",
            "date": "31 AGO 2026",
        },
        {
            "layout": "editorial",
            "eyebrow": "01 · SOBRE BPM TECH",
            "title": "DE LA IDEA AL PRODUCTO FUNCIONANDO.",
            "body": "Diseñamos y construimos tecnología alrededor de procesos reales: desde la primera definición hasta el lanzamiento y la evolución.",
            "aside_label": "ENFOQUE",
            "aside": "Entender antes de construir. Entregar por fases. Medir el valor en el uso cotidiano.",
        },
        {
            "layout": "pillars",
            "eyebrow": "02 · PROBLEMAS QUE RESOLVEMOS",
            "title": "CUANDO LA OPERATIVA YA NO CABE EN LAS HERRAMIENTAS",
            "lead": "Intervenimos donde el trabajo manual, la fragmentación o una mala experiencia frenan al equipo.",
            "items": [
                {"index": "P.01", "title": "Procesos manuales", "body": "Datos que se copian, validaciones repetidas y tareas que dependen de memoria.", "signal": "AUTOMATIZAR"},
                {"index": "P.02", "title": "Sistemas aislados", "body": "ERP, CRM y plataformas externas que no comparten información consistente.", "signal": "INTEGRAR"},
                {"index": "P.03", "title": "Software que no encaja", "body": "Herramientas estándar que obligan al negocio a trabajar contra su propio proceso.", "signal": "ADAPTAR"},
                {"index": "P.04", "title": "Decisiones sin contexto", "body": "Información dispersa que hace difícil saber qué ocurre y qué priorizar.", "signal": "VISIBILIZAR"},
            ],
        },
        {
            "layout": "table",
            "eyebrow": "03 · SERVICIOS",
            "title": "CAPACIDADES PARA CONSTRUIR LA PIEZA QUE FALTA",
            "lead": "El punto de partida puede ser una aplicación, una web, una automatización o una decisión tecnológica.",
            "headers": ["REF.", "SERVICIO", "PARA QUÉ"],
            "widths": [1.18, 3.45, 7.26],
            "row_height": 0.46,
            "rows": [
                ["S.01", "Software a medida", "Plataformas de gestión y herramientas internas alrededor de procesos propios."],
                ["S.02", "Aplicaciones web", "Portales, áreas privadas y paneles desde el prototipo hasta producción."],
                ["S.03", "Webs a medida", "Experiencias corporativas o de evento con identidad y diseño propios."],
                ["S.04", "Automatización", "Menos trabajo manual, menos errores y trazabilidad completa."],
                ["S.05", "IA aplicada", "Lectura de documentos y conocimiento interno cuando el caso aporta valor."],
                ["S.06", "Integraciones y APIs", "Sistemas conectados con errores controlados y datos consistentes."],
                ["S.07", "Consultoría tecnológica", "Problema, prioridades y hoja de ruta antes de escribir código."],
            ],
            "note": "CAPACIDADES PUBLICADAS EN LA WEB CORPORATIVA DE BPM TECH",
        },
        {
            "layout": "pillars",
            "eyebrow": "04 · QUÉ NOS DIFERENCIA",
            "title": "CRITERIO TÉCNICO CON RESPONSABILIDAD DE PRODUCTO",
            "lead": "La solución se diseña con el negocio, se prueba pronto y evoluciona con uso real.",
            "dark": True,
            "items": [
                {"index": "D.01", "title": "Contexto real", "body": "Analizamos el problema con quienes lo viven cada día, no solo con quien lo encarga.", "signal": "ESCUCHAR"},
                {"index": "D.02", "title": "Alcance consciente", "body": "Decidimos qué aporta en la primera versión y qué debe esperar.", "signal": "PRIORIZAR"},
                {"index": "D.03", "title": "Entregas visibles", "body": "Ciclos cortos para probar software funcionando durante la construcción.", "signal": "VALIDAR"},
                {"index": "D.04", "title": "Tecnología útil", "body": "Recomendamos IA y automatización donde aportan, y también decimos dónde no.", "signal": "ELEGIR"},
            ],
        },
        {
            "layout": "process",
            "eyebrow": "05 · CÓMO TRABAJAMOS",
            "title": "UN MÉTODO POR FASES, CON RESULTADOS VISIBLES",
            "lead": "Cada etapa reduce incertidumbre y deja un entregable concreto.",
            "steps": [
                {"index": "1.0", "title": "Entendemos", "body": "Mapa del problema"},
                {"index": "2.0", "title": "Diseñamos", "body": "Definición y plan"},
                {"index": "3.0", "title": "Construimos", "body": "Software iterativo"},
                {"index": "4.0", "title": "Lanzamos", "body": "Producto en uso"},
                {"index": "5.0", "title": "Evolucionamos", "body": "Hoja de ruta viva"},
            ],
            "result_label": "PRINCIPIO",
            "result": "Cada pocas semanas hay algo nuevo que el equipo puede probar y discutir.",
        },
        {
            "layout": "product_showcase",
            "eyebrow": "06 · IDENTIDAD EN PRODUCTO",
            "title": "LA MARCA TAMBIÉN FUNCIONA EN PANTALLA",
            "lead": "La web corporativa traduce la misma voz editorial: directa, técnica y sin artificios.",
            "image": "screenshots/bpm-tech-web-hero.png",
            "caption": "FIG. 01 · CAPTURA REAL DE LA WEB CORPORATIVA BPM TECH",
            "points": [
                {"index": "01", "title": "Mensaje directo", "body": "La propuesta de valor abre la experiencia sin rodeos."},
                {"index": "02", "title": "Jerarquía editorial", "body": "Tipografía, espacio y contraste organizan la lectura."},
                {"index": "03", "title": "Sistema coherente", "body": "Paper, ink y cobalt se mantienen entre web y documentos."},
                {"index": "04", "title": "Acción concreta", "body": "El recorrido conduce a explicar el proyecto real."},
            ],
        },
        {
            "layout": "split",
            "eyebrow": "07 · EJEMPLO DE PROBLEMA",
            "title": "UN ALMACÉN QUE DEPENDÍA DEL PAPEL Y LA MEMORIA",
            "lead": "Caso real anonimizado de una pyme industrial recogido en el portfolio de BPM Tech.",
            "left": {"label": "PUNTO DE PARTIDA", "title": "EL STOCK NO ERA VISIBLE", "items": ["Referencias registradas en papel", "Ubicaciones conocidas por pocas personas", "Paseos para encontrar material", "Pedidos que salían tarde"]},
            "right": {"label": "NECESIDAD", "title": "CONTROLAR EL FLUJO REAL", "items": ["Identificar cada ubicación", "Registrar entradas y movimientos", "Guiar el picking con códigos", "Mantener inventario continuo"]},
        },
        {
            "layout": "scope_split",
            "eyebrow": "08 · SOLUCIÓN PROPUESTA",
            "title": "UN WMS A LA MEDIDA DEL ALMACÉN REAL",
            "lead": "El sistema se organiza por fases para poner en uso el núcleo antes de ampliar.",
            "included": {"label": "PRIMERA VERSIÓN", "title": "CONTROL OPERATIVO", "items": ["Mapa de ubicaciones", "Entradas de material", "Referencias y stock", "Permisos por rol", "Registro de movimientos"]},
            "excluded": {"label": "EVOLUCIÓN POSTERIOR", "title": "CAPACIDADES ADICIONALES", "items": ["Picking con lectura de códigos", "Inventario continuo", "Integraciones externas", "Analítica operativa", "Nuevos flujos del almacén"]},
        },
        {
            "layout": "architecture",
            "eyebrow": "09 · ARQUITECTURA DE ALTO NIVEL",
            "title": "UNA BASE SIMPLE PARA CRECER SIN REHACER",
            "lead": "Separación clara entre interfaz, lógica, datos y conexiones con la operativa física.",
            "nodes": ["Operario", "Next.js", "Node.js", "PostgreSQL", "Códigos / APIs"],
            "details": [
                {"label": "INTERFAZ", "body": "Flujos rápidos para recepción, ubicación y picking."},
                {"label": "REGLAS", "body": "Permisos, estados y validaciones centralizadas."},
                {"label": "DATOS", "body": "Referencias, ubicaciones y movimientos trazables."},
                {"label": "CONEXIONES", "body": "Lectura de códigos e integraciones desacopladas."},
            ],
            "note": "ARQUITECTURA DE REFERENCIA BASADA EN EL CASO WMS PUBLICADO · AJUSTABLE AL CONTEXTO",
        },
        {
            "layout": "phases",
            "eyebrow": "10 · FASES",
            "title": "CONSTRUIR, USAR Y APRENDER EN EL ALMACÉN REAL",
            "lead": "El caso se desplegó progresivamente para validar cada bloque antes del siguiente.",
            "phases": [
                {"index": "01", "title": "Base", "objective": "Ordenar el mapa", "deliverable": "Ubicaciones y entradas", "duration": "Según alcance"},
                {"index": "02", "title": "Picking", "objective": "Guiar la salida", "deliverable": "Lectura de códigos", "duration": "Según alcance", "active": True},
                {"index": "03", "title": "Inventario", "objective": "Mantener control", "deliverable": "Inventario continuo", "duration": "Según alcance"},
                {"index": "04", "title": "Evolución", "objective": "Mejorar con uso", "deliverable": "Hoja de ruta", "duration": "Continua"},
            ],
        },
        {
            "layout": "case_study",
            "eyebrow": "11 · CASO REAL ANONIMIZADO",
            "title": "UN CLUB DE PÁDEL GESTIONADO DESDE UN ÚNICO SISTEMA",
            "lead": "Proyecto real publicado sin datos de cliente en el portfolio de BPM Tech.",
            "context": "Un club gestionaba reservas, cobros, socios y competiciones desde canales separados.",
            "problem": "Las reservas llegaban por teléfono y WhatsApp; los cobros y listas dependían de trabajo manual.",
            "solution": "Una plataforma con portal para el jugador y panel para administrar pistas, cuotas y torneos.",
            "result": "El club opera reservas, pagos y competiciones desde un único panel, puesto en producción por fases.",
            "technology": ["Next.js", "TypeScript", "PostgreSQL", "Supabase", "Pagos online"],
        },
        {
            "layout": "stack",
            "eyebrow": "12 · STACK TECNOLÓGICO",
            "title": "UNA BASE MODERNA, ELEGIDA POR ADECUACIÓN",
            "lead": "Tecnologías presentes en los proyectos reales publicados por BPM Tech.",
            "groups": [
                {"label": "PRODUCTO WEB", "items": ["Next.js", "React", "TypeScript"]},
                {"label": "SERVICIOS", "items": ["Node.js", "APIs", "Webhooks"]},
                {"label": "DATOS", "items": ["PostgreSQL", "Supabase"]},
                {"label": "IA Y DOCUMENTOS", "items": ["Anthropic", "RAG", "OCR"]},
                {"label": "DESPLIEGUE", "items": ["Vercel", "CI/CD"]},
            ],
            "note": "EL STACK FINAL DEPENDE DEL PROBLEMA, LAS RESTRICCIONES Y EL SISTEMA EXISTENTE",
        },
        {
            "layout": "split",
            "eyebrow": "13 · MODELO DE COLABORACIÓN",
            "title": "UN EQUIPO COMPARTIDO ALREDEDOR DE LA MISMA DECISIÓN",
            "lead": "BPM Tech aporta dirección de producto y ejecución técnica; el cliente aporta contexto y validación.",
            "left": {"label": "BPM TECH", "title": "DISEÑO Y CONSTRUCCIÓN", "items": ["Facilitar el descubrimiento", "Proponer alcance y arquitectura", "Construir y probar el producto", "Preparar despliegue y evolución"]},
            "right": {"label": "EQUIPO CLIENTE", "title": "CONTEXTO Y VALIDACIÓN", "items": ["Aportar conocimiento operativo", "Nombrar responsables de decisión", "Probar entregas en contexto", "Priorizar con información real"]},
        },
        {
            "layout": "next_steps",
            "eyebrow": "14 · PRÓXIMOS PASOS",
            "title": "EMPEZAR POR EL PROBLEMA, NO POR LA SOLUCIÓN",
            "lead": "Una conversación breve permite decidir si existe un caso claro para avanzar.",
            "steps": [
                {"index": "01", "action": "Compartir el contexto", "body": "Proceso actual, personas implicadas, herramientas y fricciones.", "timing": "PRIMERA CONVERSACIÓN"},
                {"index": "02", "action": "Delimitar la oportunidad", "body": "Objetivo, alcance inicial, riesgos y preguntas abiertas.", "timing": "SESIÓN DE TRABAJO"},
                {"index": "03", "action": "Trazar la primera fase", "body": "Entregable útil, responsables y criterio de validación.", "timing": "PROPUESTA"},
            ],
        },
        {
            "layout": "corporate_closing",
            "eyebrow": "15 · BPM TECH",
            "title": "CONSTRUIMOS EL SOFTWARE QUE VUESTRO NEGOCIO NECESITA.",
            "lead": "Aplicaciones a medida, automatización e inteligencia artificial desde Valencia, España.",
            "cta": "CUÉNTANOS TU PROYECTO",
            "contact": "VALENCIA · ESPAÑA",
        },
    ],
}
