DECK = {
    "meta": {
        "title": "BPM Tech · Sistema de propuestas comerciales",
        "subject": "Propuesta interna demostrativa · WS2.X",
        "author": "BPM Tech",
        "company": "BPM Tech",
        "comments": "Deck demostrativo. No constituye una oferta económica.",
    },
    "slides": [
        {
            "layout": "cover",
            "eyebrow": "PROPUESTA INTERNA · WS2.X",
            "client": "BPM TECH / SISTEMA COMERCIAL",
            "title": "PROPUESTAS QUE SE SIENTEN HECHAS A MEDIDA",
            "subtitle": "Un framework editable para convertir contexto, alcance y decisión comercial en una historia clara.",
            "status": "DEMOSTRADOR · VALIDACIÓN INTERNA",
            "confidentiality": "DOCUMENTO DE TRABAJO",
            "date": "31 AGO 2026",
        },
        {
            "layout": "understanding",
            "eyebrow": "LO QUE HEMOS ENTENDIDO",
            "title": "CADA PROPUESTA DEBE PARECER HECHA UNA VEZ. EL SISTEMA, MUCHAS",
            "lead": "El reto no es producir más diapositivas. Es sostener una conversación comercial específica sin perder rigor, identidad ni control de alcance.",
            "points": [
                {
                    "index": "01 · ESPECÍFICA",
                    "title": "EL CLIENTE SE RECONOCE",
                    "body": "Su contexto, lenguaje y operativa aparecen antes que nuestras capacidades.",
                },
                {
                    "index": "02 · PRECISA",
                    "title": "EL ALCANCE NO SE DILUYE",
                    "body": "Incluido, evolución futura y exclusiones quedan separados y son fáciles de localizar.",
                },
                {
                    "index": "03 · REPETIBLE",
                    "title": "LA CALIDAD NO DEPENDE DEL DÍA",
                    "body": "Marca, narrativa, componentes y control visual funcionan como un mismo sistema.",
                },
            ],
        },
        {
            "layout": "solution",
            "eyebrow": "QUÉ PROPONEMOS",
            "title": "NARRATIVA PRIMERO. LAYOUT DESPUÉS",
            "lead": "La propuesta se compone a partir de la decisión que debe facilitar cada página, no desde un catálogo de plantillas.",
            "pillars": [
                {
                    "index": "01",
                    "title": "CONTEXTO",
                    "body": "Problema, operativa actual, lenguaje del sector y criterio de éxito.",
                },
                {
                    "index": "02",
                    "title": "HISTORIA",
                    "body": "Secuencia de preguntas comerciales que el documento debe responder.",
                },
                {
                    "index": "03",
                    "title": "SISTEMA",
                    "body": "Layouts y componentes editables seleccionados según la intención narrativa.",
                },
                {
                    "index": "04",
                    "title": "CONTROL",
                    "body": "Render completo, detección de desbordes, revisión visual y exportación PDF.",
                },
            ],
        },
        {
            "layout": "evidence",
            "eyebrow": "NO PARTIMOS DE UNA IDEA ABSTRACTA",
            "title": "LA IDENTIDAD YA ESTÁ VIVA",
            "lead": "El sistema traslada a presentación los mismos principios que ya ordenan la web actual de BPM Tech.",
            "image": "screenshots/bpm-tech-web-hero.png",
            "proofs": [
                {
                    "index": "01",
                    "title": "Una voz reconocible",
                    "body": "Archivo Black, caja alta y mensajes que se entienden antes de entrar en detalle.",
                },
                {
                    "index": "02",
                    "title": "Un solo acento",
                    "body": "Cobalto para guiar la mirada; papel y tinta sostienen el resto de la composición.",
                },
                {
                    "index": "03",
                    "title": "Estructura editorial",
                    "body": "Hairlines, márgenes técnicos y bloques sin sombras ni artificios visuales.",
                },
            ],
            "caption": "FIG. 01 · HOME ACTUAL DE BPM TECH · CAPTURA LOCAL 31/08/2026",
        },
        {
            "layout": "process",
            "eyebrow": "CÓMO FUNCIONA",
            "title": "DEL BRIEF AL DOCUMENTO ENVIABLE",
            "lead": "Un flujo corto obliga a cerrar la historia antes de producir y convierte el control visual en parte del entregable.",
            "steps": [
                {"index": "01", "title": "Escuchar", "body": "Contexto, dolor y decisión pendiente."},
                {"index": "02", "title": "Enmarcar", "body": "Problema, promesa y prueba tangible."},
                {"index": "03", "title": "Secuenciar", "body": "Una función narrativa por página."},
                {"index": "04", "title": "Componer", "body": "Layout y componentes adecuados."},
                {"index": "05", "title": "Revisar", "body": "Render, contraste, densidad y overflow."},
                {"index": "06", "title": "Entregar", "body": "PPTX editable y PDF comprobado."},
            ],
            "result_label": "RESULTADO",
            "result": "Una propuesta que el equipo comercial puede defender y el cliente puede decidir.",
        },
        {
            "layout": "scope",
            "eyebrow": "ALCANCE DEL SISTEMA",
            "title": "QUÉ ESTAMOS CONSTRUYENDO EXACTAMENTE",
            "lead": "Las piezas se separan para que la identidad permanezca estable y el contenido cambie con cada oportunidad.",
            "items": [
                {"index": "01", "title": "Tema de marca", "body": "Color, tipografía, retícula, contraste y reglas de uso."},
                {"index": "02", "title": "Narrativa", "body": "Secuencia comercial y criterio de entrada de cada slide."},
                {"index": "03", "title": "Layouts", "body": "Composiciones editoriales, técnicas y económicas."},
                {"index": "04", "title": "Componentes", "body": "Titulares, footers, matrices, procesos, diagramas y callouts."},
                {"index": "05", "title": "Contenido", "body": "Datos del cliente aislados del código visual."},
                {"index": "06", "title": "Activos", "body": "Capturas, diagramas y evidencias reales del producto."},
                {"index": "07", "title": "Salida editable", "body": "Texto, formas, líneas y tablas siguen siendo editables."},
                {"index": "08", "title": "Control de calidad", "body": "Render por página, QA de texto y validación final del PDF."},
            ],
        },
        {
            "layout": "detail",
            "eyebrow": "FUNCIONALIDAD CLAVE · ORQUESTACIÓN",
            "title": "LA HISTORIA DECIDE LA COMPOSICIÓN",
            "lead": "Cada señal del brief activa una respuesta narrativa y un patrón visual. Lo que no aporta a la decisión no entra.",
            "rows": [
                {"index": "01", "signal": "Dolor poco concreto", "choice": "Statement + comprensión", "active": False},
                {"index": "02", "signal": "Existe prototipo", "choice": "Evidencia visual temprana", "active": True},
                {"index": "03", "signal": "Proceso complejo", "choice": "Flujo paso a paso", "active": False},
                {"index": "04", "signal": "Alcance sensible", "choice": "Índice + detalle + exclusiones", "active": False},
                {"index": "05", "signal": "Integraciones", "choice": "Arquitectura para cliente", "active": False},
            ],
            "notes": [
                {"label": "PRINCIPIO 01", "body": "Una página, una función narrativa. La composición cambia cuando cambia la pregunta."},
                {"label": "PRINCIPIO 02", "body": "Mostrar producto real antes de pedir confianza en una explicación técnica."},
                {"label": "PRINCIPIO 03", "body": "Diferenciar presente y futuro para demostrar visión sin ampliar el presupuesto."},
            ],
        },
        {
            "layout": "gallery",
            "eyebrow": "SISTEMA VISUAL FLEXIBLE",
            "title": "DISTINTAS PÁGINAS. UNA MISMA EMPRESA",
            "lead": "La variación sostiene el ritmo; la retícula, la voz y los materiales mantienen la identidad.",
            "items": [
                {"label": "STATEMENT", "purpose": "Enmarcar una idea", "dark": True},
                {"label": "ALCANCE", "purpose": "Precisar lo incluido"},
                {"label": "EVIDENCIA", "purpose": "Mostrar producto real"},
                {"label": "PROCESO", "purpose": "Explicar cómo funciona"},
                {"label": "ARQUITECTURA", "purpose": "Hacer visible el sistema", "dark": True},
                {"label": "ROLES", "purpose": "Aclarar responsabilidades"},
                {"label": "INVERSIÓN", "purpose": "Facilitar la decisión"},
                {"label": "CIERRE", "purpose": "Provocar el siguiente paso", "dark": True},
            ],
        },
        {
            "layout": "roles",
            "eyebrow": "ROLES Y RESPONSABILIDADES",
            "title": "EL SISTEMA ORDENA QUIÉN DECIDE QUÉ",
            "lead": "La propuesta se personaliza mejor cuando cada persona aporta la información que conoce y valida la parte que le corresponde.",
            "roles": [
                {"index": "01 · COMERCIAL", "title": "CONTEXTO", "body": "Recoge el problema, el lenguaje del cliente, la decisión pendiente y el siguiente paso."},
                {"index": "02 · DELIVERY", "title": "ALCANCE", "body": "Define funcionalidades, límites, supuestos, dependencias, arquitectura y plan realista."},
                {"index": "03 · CLIENTE", "title": "VALIDACIÓN", "body": "Confirma procesos, prioridades, responsables, integraciones y criterios de aceptación."},
                {"index": "04 · SISTEMA", "title": "CONSISTENCIA", "body": "Aplica identidad, compone, pagina, exporta y señala posibles desbordes antes de enviar."},
            ],
            "traceability": "QUEDA REGISTRADO · VERSIÓN · FECHA · ESTADO · SUPUESTOS · INCLUIDO · NO INCLUIDO · SIGUIENTE PASO",
        },
        {
            "layout": "architecture",
            "eyebrow": "ARQUITECTURA DEL SISTEMA",
            "title": "CONTENIDO SEPARADO DE LA PRESENTACIÓN",
            "lead": "El cliente cambia en la capa de contenido. Marca, layouts y componentes evolucionan sin reescribir cada propuesta.",
            "nodes": ["BRIEF", "NARRATIVA", "CONTENIDO", "LAYOUTS", "PPTX + PDF"],
            "details": [
                {"label": "THEME", "body": "Tokens de marca, fuentes, retícula, contraste y numeración."},
                {"label": "LAYOUTS", "body": "Patrones ligados a una intención narrativa concreta."},
                {"label": "COMPONENTS", "body": "Primitivas editables: texto, formas, líneas y diagramas."},
                {"label": "QA", "body": "Exportación por slide, detección de overflow y revisión visual."},
            ],
            "note": "INTEGRACIONES FUTURAS POSIBLES · CRM · FORMULARIO DE DISCOVERY · REPOSITORIO DE CAPTURAS · APROBACIONES",
        },
        {
            "layout": "horizons",
            "eyebrow": "EVOLUCIÓN FUTURA",
            "title": "VISIÓN SIN CONFUNDIRLA CON EL ALCANCE",
            "lead": "El sistema demuestra hacia dónde puede crecer, pero protege explícitamente lo que se entrega en esta fase.",
            "current": {
                "label": "ALCANCE ACTUAL",
                "title": "BASE REUTILIZABLE Y EDITABLE",
                "items": ["Tema BPM Tech", "15 patrones narrativos", "Ejemplo completo", "PPTX, PDF y control visual"],
            },
            "future": {
                "label": "POSIBLES EVOLUCIONES",
                "title": "MÁS AUTOMATIZACIÓN, MISMO CRITERIO",
                "items": ["Brief conectado a CRM", "Biblioteca de evidencias", "Versionado y aprobaciones", "Métricas de propuestas"],
            },
        },
        {
            "layout": "implementation",
            "eyebrow": "PLAN DE IMPLANTACIÓN",
            "title": "DE LA OPORTUNIDAD AL ENVÍO",
            "lead": "Las fechas se fijan cuando existe alcance. El orden de validación, en cambio, debe permanecer estable.",
            "steps": [
                {"index": "01", "title": "Descubrimiento", "body": "Problema, audiencia y decisión."},
                {"index": "02", "title": "Validación", "body": "Contexto y prioridades con el cliente."},
                {"index": "03", "title": "Cierre de alcance", "body": "Incluido, límites y supuestos."},
                {"index": "04", "title": "Aceptación", "body": "Marco económico y siguiente paso."},
                {"index": "05", "title": "Producción", "body": "Contenido y evidencia real."},
                {"index": "06", "title": "Revisión", "body": "Comercial, técnica y visual."},
                {"index": "07", "title": "Entrega", "body": "PPTX editable y PDF final."},
                {"index": "08", "title": "Seguimiento", "body": "Reunión y control de versión."},
            ],
            "note": "NO SE INVENTAN FECHAS · EL CALENDARIO SE ACUERDA TRAS VALIDAR ALCANCE Y DISPONIBILIDAD",
        },
        {
            "layout": "investment",
            "eyebrow": "INVERSIÓN · PATRÓN DEMOSTRATIVO",
            "title": "PRECIO, RECURRENCIA Y CONDICIONES A LA VISTA",
            "lead": "Esta página valida la estructura comercial. Las cifras permanecen abiertas porque este documento interno no constituye una oferta.",
            "blocks": [
                {
                    "label": "DESARROLLO / IMPLANTACIÓN",
                    "value": "A DEFINIR",
                    "items": ["Tras validar el alcance", "Importe + IVA", "Hitos de facturación visibles"],
                },
                {
                    "label": "SERVICIO / MANTENIMIENTO",
                    "value": "SEGÚN NECESIDAD",
                    "items": ["Cuota mensual + IVA", "Infraestructura detallada", "Consumo extraordinario aprobado"],
                },
                {
                    "label": "CONDICIONES",
                    "value": "SIN LETRA ESCONDIDA",
                    "items": ["Qué incluye cada importe", "Cuándo se factura", "Forma de pago", "Validez de la propuesta"],
                    "dark": True,
                },
            ],
            "note": "DOCUMENTO DEMOSTRATIVO · LOS IMPORTES SE COMPLETAN SOLO CON INFORMACIÓN COMERCIAL VALIDADA",
        },
        {
            "layout": "exclusions",
            "eyebrow": "PROTECCIÓN DEL ALCANCE",
            "title": "NO INCLUIDO",
            "lead": "Lo que no está descrito no se presume. Se valida, se estima y se aprueba antes de ejecutarlo.",
            "items": [
                {"index": "01", "title": "Hardware", "body": "Dispositivos, terminales y equipos físicos."},
                {"index": "02", "title": "Nuevas funciones", "body": "Capacidades no descritas en el alcance."},
                {"index": "03", "title": "Integraciones", "body": "Conexiones externas no identificadas."},
                {"index": "04", "title": "Migraciones", "body": "Volúmenes y saneado no acordados."},
                {"index": "05", "title": "Licencias", "body": "Productos de terceros y sus consumos."},
                {"index": "06", "title": "Evolutivos", "body": "Fases futuras y cambios de prioridad."},
                {"index": "07", "title": "Contenido", "body": "Redacción o activos no entregados."},
                {"index": "08", "title": "Urgencias", "body": "Aceleraciones no contempladas en el plan."},
            ],
            "note": "CUALQUIER AMPLIACIÓN SE VALORA Y PRESUPUESTA ANTES DE SU EJECUCIÓN",
        },
        {
            "layout": "closing",
            "eyebrow": "PRÓXIMO PASO",
            "title": "VALIDEMOS JUNTOS EL SISTEMA",
            "action_label": "SESIÓN DE VALIDACIÓN · 60 MIN",
            "action_title": "UNA REVISIÓN CON DECISIONES CONCRETAS",
            "action_body": "El objetivo es cerrar el marco y dejar lista la primera propuesta real.",
            "checklist_label": "QUÉ CERraREMOS EN LA SESIÓN".upper(),
            "checklist": [
                "Orden narrativo y slides obligatorias",
                "Datos mínimos del brief comercial",
                "Reglas de inversión y no incluido",
                "Cliente piloto y responsable de contenido",
            ],
            "brand": "BPM TECH",
            "descriptor": "TECNOLOGÍA A MEDIDA PARA EMPRESAS · VALENCIA",
            "version": "WS2.X · DEMO V01 · 31 AGO 2026",
        },
    ],
}
