DECK = {
    "meta": {
        "title": "Propuesta ficticia · Río Turia Mantenimiento · Portal de operaciones",
        "subject": "Caso demostrativo con condiciones comerciales completas",
        "author": "BPM Tech",
        "company": "BPM Tech",
        "comments": "Empresa, contexto y cifras ficticios. Documento de demostración.",
    },
    "slides": [
        {
            "layout": "cover",
            "eyebrow": "PROPUESTA COMERCIAL · CASO FICTICIO",
            "client": "RÍO TURIA MANTENIMIENTO / OPERACIONES",
            "title": "DEL AVISO AL PARTE FIRMADO, SIN PERDER INFORMACIÓN",
            "subtitle": "Portal web para coordinar órdenes de trabajo, técnicos, evidencias y comunicación con clientes.",
            "status": "V1.0 · VALIDEZ 30/09/2026",
            "confidentiality": "EMPRESA Y DATOS FICTICIOS · DEMOSTRACIÓN",
            "date": "31 AGO 2026",
        },
        {
            "layout": "understanding",
            "eyebrow": "LO QUE RÍO TURIA NECESITA",
            "title": "UNA OPERATIVA DE MANTENIMIENTO MÁS VISIBLE, ÁGIL Y TRAZABLE",
            "lead": "Hoy cada aviso atraviesa correo, Excel, WhatsApp y documentos Word. El equipo trabaja, pero reconstruir qué ocurrió consume tiempo y genera dudas al cliente.",
            "points": [
                {
                    "index": "01 · COORDINACIÓN",
                    "title": "UNA SOLA COLA DE TRABAJO",
                    "body": "Avisos, prioridad, agenda, técnico y estado visibles sin perseguir conversaciones.",
                },
                {
                    "index": "02 · CAMPO",
                    "title": "EL TÉCNICO RESUELVE DESDE EL MÓVIL",
                    "body": "Tareas, materiales, fotografías, tiempos y firma registrados durante la intervención.",
                },
                {
                    "index": "03 · CLIENTE",
                    "title": "CADA CIERRE DEJA UNA PRUEBA",
                    "body": "Parte PDF, evidencias e histórico disponibles sin rehacer información al final del día.",
                },
            ],
        },
        {
            "layout": "solution",
            "eyebrow": "QUÉ PROPONEMOS",
            "title": "UN PORTAL OPERATIVO DE PRINCIPIO A FIN",
            "lead": "Una aplicación web compartida por coordinación, técnicos y clientes, con una experiencia adaptada al trabajo de cada rol.",
            "pillars": [
                {"index": "01", "title": "RECEPCIÓN", "body": "Avisos por portal o alta interna, con cliente, ubicación, prioridad y documentación."},
                {"index": "02", "title": "PLANIFICACIÓN", "body": "Agenda de técnicos, asignación, estados y vista de carga diaria y semanal."},
                {"index": "03", "title": "INTERVENCIÓN", "body": "Checklist, tiempos, materiales, fotos, observaciones y firma desde móvil."},
                {"index": "04", "title": "CIERRE", "body": "Parte PDF automático, envío al cliente, histórico y cuadro de seguimiento."},
            ],
        },
        {
            "layout": "prototype",
            "eyebrow": "PROTOTIPO CONCEPTUAL",
            "title": "LA OPERATIVA YA SE PUEDE VER",
            "lead": "Esta representación editable valida la jerarquía de información y el flujo principal; el diseño funcional definitivo se cerrará con los usuarios.",
            "metrics": [
                {"label": "ABIERTAS", "value": "18"},
                {"label": "EN CURSO", "value": "7"},
                {"label": "HOY", "value": "12"},
            ],
            "orders": [
                {"id": "0248", "client": "Hotel Azahar", "task": "Revisión climatización", "tech": "M. Costa", "status": "EN CURSO"},
                {"id": "0247", "client": "Nave Levante", "task": "Fuga circuito hidráulico", "tech": "J. Soler", "status": "ASIGNADA"},
                {"id": "0245", "client": "Clínica Mar", "task": "Preventivo trimestral", "tech": "A. Vidal", "status": "PENDIENTE"},
            ],
            "mobile": {
                "order": "OT-0248",
                "status": "EN CURSO",
                "client": "Hotel Azahar",
                "address": "Av. del Puerto 214 · Valencia",
                "checks": ["Equipo identificado", "Diagnóstico registrado", "Añadir firma del cliente"],
            },
            "caption": "FIG. 01 · PROTOTIPO CONCEPTUAL · DATOS Y EMPRESA FICTICIOS",
        },
        {
            "layout": "process",
            "eyebrow": "OPERATIVA PRINCIPAL",
            "title": "UN MISMO HILO DESDE EL AVISO HASTA EL CIERRE",
            "lead": "Cada cambio de estado tiene responsable, fecha y siguiente acción. Las personas no tienen que reconstruir el proceso después.",
            "steps": [
                {"index": "01", "title": "Aviso", "body": "Cliente, ubicación, problema y prioridad."},
                {"index": "02", "title": "Validación", "body": "Coordinación revisa datos y urgencia."},
                {"index": "03", "title": "Asignación", "body": "Técnico, fecha y franja previstas."},
                {"index": "04", "title": "Intervención", "body": "Tareas, tiempos, material y evidencias."},
                {"index": "05", "title": "Firma", "body": "Conformidad u observaciones del cliente."},
                {"index": "06", "title": "Cierre", "body": "Parte PDF enviado e histórico actualizado."},
            ],
            "result_label": "RESULTADO",
            "result": "Una orden trazable, consultable y defendible desde el primer aviso.",
        },
        {
            "layout": "scope",
            "eyebrow": "ALCANCE FUNCIONAL",
            "title": "PRIMERA VERSIÓN LISTA PARA OPERAR",
            "lead": "El alcance prioriza el ciclo diario completo. Todo lo necesario para recibir, planificar, ejecutar y cerrar una orden queda incluido.",
            "items": [
                {"index": "01", "title": "Clientes y centros", "body": "Contactos, ubicaciones, equipos y datos de acceso."},
                {"index": "02", "title": "Avisos y órdenes", "body": "Alta, prioridad, adjuntos, estados y responsable."},
                {"index": "03", "title": "Agenda de técnicos", "body": "Asignación y carga diaria o semanal por persona."},
                {"index": "04", "title": "App web de campo", "body": "Checklist, tiempos, materiales, fotos y notas."},
                {"index": "05", "title": "Firma y conformidad", "body": "Firma táctil y observaciones del cliente."},
                {"index": "06", "title": "Partes PDF", "body": "Generación automática y envío por correo."},
                {"index": "07", "title": "Roles y trazabilidad", "body": "Permisos e histórico de cada cambio relevante."},
                {"index": "08", "title": "Cuadro de seguimiento", "body": "Pendientes, carga, tiempos y cierres por periodo."},
            ],
        },
        {
            "layout": "detail",
            "eyebrow": "FUNCIONALIDAD CLAVE · PARTE DIGITAL",
            "title": "DEL TRABAJO REAL AL PARTE FIRMADO",
            "lead": "El técnico registra una sola vez. El sistema organiza la información y genera el documento que recibe el cliente.",
            "rows": [
                {"index": "01", "signal": "Inicio de intervención", "choice": "Fecha, técnico y centro registrados", "active": False},
                {"index": "02", "signal": "Trabajo realizado", "choice": "Tareas, tiempos y materiales estructurados", "active": False},
                {"index": "03", "signal": "Evidencias", "choice": "Fotografías y observaciones asociadas", "active": False},
                {"index": "04", "signal": "Conformidad", "choice": "Firma y nombre de la persona receptora", "active": True},
                {"index": "05", "signal": "Cierre", "choice": "PDF generado, enviado y archivado", "active": False},
            ],
            "notes": [
                {"label": "UN SOLO FORMATO", "body": "La plantilla del parte se acuerda antes del desarrollo y se aplica a todas las órdenes."},
                {"label": "TRAZABILIDAD", "body": "Cada edición relevante conserva autor, fecha y estado de la orden."},
                {"label": "VALIDACIÓN", "body": "Campos, firma y evidencias se probarán con dos técnicos antes del piloto."},
            ],
        },
        {
            "layout": "roles",
            "eyebrow": "USUARIOS Y TRAZABILIDAD",
            "title": "CADA PERSONA VE LO QUE NECESITA",
            "lead": "Los permisos reducen ruido y protegen información. La matriz final se valida durante el descubrimiento.",
            "roles": [
                {"index": "01 · ADMIN", "title": "CONFIGURA", "body": "Usuarios, permisos, catálogos, plantillas y parámetros generales."},
                {"index": "02 · COORDINACIÓN", "title": "ORGANIZA", "body": "Valida avisos, asigna técnicos, prioriza y consulta toda la operativa."},
                {"index": "03 · TÉCNICO", "title": "EJECUTA", "body": "Consulta su agenda y registra tareas, tiempos, materiales, fotos y firma."},
                {"index": "04 · CLIENTE", "title": "CONSULTA", "body": "Crea avisos, sigue estados y accede a partes de sus propios centros."},
            ],
            "traceability": "QUEDA REGISTRADO · ORDEN · ESTADO · FECHA Y HORA · USUARIO · TAREAS · MATERIAL · EVIDENCIAS · FIRMA",
        },
        {
            "layout": "architecture",
            "eyebrow": "ARQUITECTURA E INTEGRACIONES",
            "title": "UNA BASE SENCILLA PARA OPERAR Y EVOLUCIONAR",
            "lead": "La solución funciona en navegador, protege cada acceso por rol y mantiene documentos y datos en servicios gestionados.",
            "nodes": ["CLIENTE", "PORTAL WEB", "API SEGURA", "POSTGRESQL", "EMAIL + PDF"],
            "details": [
                {"label": "EXPERIENCIA", "body": "Aplicación web adaptable para oficina, tablet y móvil."},
                {"label": "SEGURIDAD", "body": "Acceso autenticado, roles y separación de datos por cliente."},
                {"label": "DATOS", "body": "PostgreSQL, almacenamiento documental y copias diarias."},
                {"label": "OPERACIÓN", "body": "Hosting gestionado, HTTPS, monitorización y registros."},
            ],
            "note": "FASE 1 · SIN INTEGRACIÓN ERP · EL INTERCAMBIO INICIAL SE REALIZA MEDIANTE PLANTILLAS EXCEL ACORDADAS",
        },
        {
            "layout": "horizons",
            "eyebrow": "EVOLUCIÓN FUTURA",
            "title": "PRIMERO CERRAR EL CICLO. DESPUÉS CONECTARLO",
            "lead": "La primera versión resuelve la operativa diaria. Las integraciones y optimizaciones se valoran con datos de uso real.",
            "current": {
                "label": "ALCANCE ACTUAL",
                "title": "PORTAL OPERATIVO COMPLETO",
                "items": ["Avisos, órdenes y agenda", "App web para técnicos", "Firma, parte PDF e histórico", "Portal de cliente y seguimiento"],
            },
            "future": {
                "label": "POSIBLES EVOLUCIONES",
                "title": "MÁS INTEGRACIÓN Y MOVILIDAD",
                "items": ["Integración con ERP", "Trabajo offline", "Rutas y geolocalización", "Analítica de costes y SLA"],
            },
        },
        {
            "layout": "implementation",
            "eyebrow": "PLAN DE IMPLANTACIÓN · 12 SEMANAS",
            "title": "DEL DESCUBRIMIENTO AL PILOTO EN CAMPO",
            "lead": "El calendario parte de la aceptación y requiere disponibilidad semanal de coordinación y dos técnicos de referencia.",
            "steps": [
                {"index": "01 · S1", "title": "Descubrimiento", "body": "Procesos, parte y matriz de roles."},
                {"index": "02 · S2", "title": "Validación", "body": "Alcance, prototipo y criterios."},
                {"index": "03 · S3–4", "title": "Diseño funcional", "body": "Flujos, datos y experiencia móvil."},
                {"index": "04 · S5–8", "title": "Núcleo operativo", "body": "Órdenes, agenda, clientes y roles."},
                {"index": "05 · S9–10", "title": "Campo y partes", "body": "Técnicos, evidencias, firma y PDF."},
                {"index": "06 · S11", "title": "Aceptación", "body": "Pruebas con datos y casos acordados."},
                {"index": "07 · S11", "title": "Formación", "body": "Dos sesiones remotas de 90 min."},
                {"index": "08 · S12", "title": "Producción", "body": "Carga inicial, piloto y acompañamiento."},
            ],
            "note": "PLAZO ESTIMADO · 12 SEMANAS DESDE KICK-OFF · SUJETO A VALIDACIÓN DE ALCANCE Y RESPUESTAS EN 2 DÍAS LABORABLES",
        },
        {
            "layout": "investment",
            "eyebrow": "PROPUESTA ECONÓMICA",
            "title": "INVERSIÓN Y CONDICIONES",
            "lead": "Importes cerrados para el alcance descrito. Cualquier ampliación se estima y aprueba antes de ejecutarla.",
            "blocks": [
                {
                    "label": "DESARROLLO / IMPLANTACIÓN",
                    "value": "14.800 € + IVA",
                    "items": ["40 % al aceptar · 5.920 €", "40 % al validar · 5.920 €", "20 % antes de producción · 2.960 €"],
                },
                {
                    "label": "SERVICIO / MANTENIMIENTO",
                    "value": "190 € / MES + IVA",
                    "items": ["Desde la puesta en producción", "Hosting, copias y monitorización", "Soporte correctivo por email"],
                },
                {
                    "label": "CONDICIONES",
                    "value": "OFERTA · 30 DÍAS",
                    "items": ["Inicio en 10 días laborables", "Hasta 15 usuarios internos", "50 GB y 1.000 emails / mes", "Importes adicionales preaprobados"],
                    "dark": True,
                },
            ],
            "note": "CASO FICTICIO · PRECIOS, EMPRESA Y CONDICIONES CREADOS PARA DEMOSTRAR UNA PROPUESTA COMPLETA",
        },
        {
            "layout": "exclusions",
            "eyebrow": "PROTECCIÓN DEL ALCANCE",
            "title": "NO INCLUIDO",
            "lead": "Los siguientes elementos no forman parte de los 14.800 € y requieren validación y presupuesto independiente.",
            "items": [
                {"index": "01", "title": "Hardware", "body": "Móviles, tablets, impresoras o equipos."},
                {"index": "02", "title": "Integración ERP", "body": "Conectores, sincronización y licencias."},
                {"index": "03", "title": "Modo offline", "body": "Trabajo sin cobertura y sincronización."},
                {"index": "04", "title": "Migración histórica", "body": "Carga distinta de plantillas acordadas."},
                {"index": "05", "title": "Geolocalización", "body": "Rutas, mapas y seguimiento continuo."},
                {"index": "06", "title": "Nuevos módulos", "body": "Facturación, compras o almacén."},
                {"index": "07", "title": "Licencias externas", "body": "Servicios de pago de terceros."},
                {"index": "08", "title": "Soporte 24/7", "body": "Guardias o SLA fuera de horario."},
            ],
            "note": "EVOLUTIVOS, CAMBIOS DE ALCANCE Y CONSUMOS EXTRAORDINARIOS SE APRUEBAN ANTES DE SU EJECUCIÓN",
        },
        {
            "layout": "closing",
            "eyebrow": "PRÓXIMO PASO · CASO FICTICIO",
            "title": "CERREMOS EL ALCANCE Y ARRANQUEMOS",
            "action_label": "SESIÓN DE CIERRE · 75 MIN",
            "action_title": "UNA REUNIÓN PARA PASAR A KICK-OFF",
            "action_body": "Con el alcance validado, BPM Tech emite la versión de firma y reserva fecha de inicio.",
            "checklist_label": "QUÉ CERraREMOS EN LA SESIÓN".upper(),
            "checklist": [
                "Flujo real de aviso, intervención y cierre",
                "Plantilla del parte y campos obligatorios",
                "Matriz de roles y clientes del piloto",
                "Aceptación, pago inicial y fecha de kick-off",
            ],
            "brand": "BPM TECH",
            "descriptor": "TECNOLOGÍA A MEDIDA PARA EMPRESAS · VALENCIA",
            "version": "CASO FICTICIO · V1.0 · 31 AGO 2026",
        },
    ],
}
