DECK = {
    "meta": {
        "title": "Plantilla corporativa BPM Tech 2026",
        "subject": "Catálogo reutilizable de 21 layouts corporativos",
        "author": "BPM Tech",
        "comments": "Sistema visual derivado de la identidad corporativa BPM Tech.",
        "footer_label": "BPM TECH · SISTEMA CORPORATIVO",
    },
    "slides": [
        {
            "layout": "cover",
            "eyebrow": "PLANTILLA CORPORATIVA · 2026",
            "client": "CLIENTE / PROYECTO",
            "title": "TÍTULO DE LA PRESENTACIÓN",
            "subtitle": "Una frase breve para explicar el propósito, la propuesta o la decisión que contiene este deck.",
            "status": "VERSIÓN 01 · DOCUMENTO DE TRABAJO",
            "confidentiality": "USO CONFIDENCIAL",
            "date": "31 AGO 2026",
        },
        {
            "layout": "section",
            "eyebrow": "02 · SEPARADOR DE SECCIÓN",
            "index": "02",
            "title": "LA SOLUCIÓN",
            "subtitle": "Una transición narrativa limpia para abrir cada bloque de la historia.",
            "signal": "CONTEXTO · DECISIÓN · SIGUIENTE CAPÍTULO",
        },
        {
            "layout": "editorial",
            "eyebrow": "03 · MENSAJE EDITORIAL",
            "title": "EL PROBLEMA NO ES EL PROCESO. ES LA HERRAMIENTA.",
            "body": "Utiliza esta composición para detener el ritmo, fijar una idea y preparar la siguiente decisión.",
            "aside_label": "USO RECOMENDADO",
            "aside": "Una afirmación contundente, una explicación breve y espacio para que el mensaje respire.",
        },
        {
            "layout": "standard",
            "eyebrow": "04 · CONTENIDO ESTÁNDAR",
            "title": "UNA ESTRUCTURA PARA EXPLICAR SIN SATURAR",
            "lead": "Texto, argumentos y un bloque visual conviven con jerarquía editorial.",
            "items": [
                {"index": "01", "title": "Punto principal", "body": "Una idea clara que se entiende en pocos segundos."},
                {"index": "02", "title": "Evidencia", "body": "Datos, observaciones o requisitos que sostienen la idea."},
                {"index": "03", "title": "Implicación", "body": "Qué cambia y por qué importa para la decisión."},
                {"index": "04", "title": "Acción", "body": "La conclusión o siguiente movimiento esperado."},
            ],
            "visual_label": "BLOQUE OPCIONAL",
            "visual_title": "GRÁFICO, DATO O\nESQUEMA",
            "visual_items": ["Contexto", "Decisión", "Resultado"],
        },
        {
            "layout": "split",
            "eyebrow": "05 · DOS COLUMNAS",
            "title": "DE LA SITUACIÓN ACTUAL A LA PROPUESTA",
            "lead": "Contrasta dos estados sin recurrir a una colección de cards genéricas.",
            "left": {"label": "SITUACIÓN ACTUAL", "title": "FRICCIÓN OPERATIVA", "items": ["Trabajo manual repetitivo", "Información fragmentada", "Errores difíciles de rastrear", "Decisiones con poca visibilidad"]},
            "right": {"label": "PROPUESTA", "title": "SISTEMA CONECTADO", "items": ["Un flujo único", "Datos consistentes", "Trazabilidad por diseño", "Evolución por fases"]},
        },
        {
            "layout": "pillars",
            "eyebrow": "06 · PILARES",
            "title": "CUATRO IDEAS, UNA SOLA DIRECCIÓN",
            "lead": "Diseñado para capacidades, principios, servicios o beneficios.",
            "items": [
                {"index": "01", "title": "Claridad", "body": "Separa lo esencial del ruido y formula una decisión concreta.", "signal": "ENTENDER"},
                {"index": "02", "title": "Precisión", "body": "Convierte necesidades abiertas en alcance verificable.", "signal": "DEFINIR"},
                {"index": "03", "title": "Progreso", "body": "Entrega por etapas visibles, útiles y evaluables.", "signal": "CONSTRUIR"},
                {"index": "04", "title": "Evolución", "body": "Mejora el producto con el aprendizaje de uso real.", "signal": "MEJORAR"},
            ],
        },
        {
            "layout": "process",
            "eyebrow": "07 · PROCESO / TIMELINE",
            "title": "UN MÉTODO QUE HACE VISIBLE EL AVANCE",
            "lead": "Cada fase termina con un resultado concreto que se puede revisar.",
            "steps": [
                {"index": "01", "title": "Entender", "body": "Problema y contexto"},
                {"index": "02", "title": "Proponer", "body": "Alcance y prioridad"},
                {"index": "03", "title": "Diseñar", "body": "Flujos y sistema"},
                {"index": "04", "title": "Construir", "body": "Iteraciones visibles"},
                {"index": "05", "title": "Evolucionar", "body": "Uso y mejora"},
            ],
            "result_label": "RESULTADO",
            "result": "Una secuencia comprensible, con responsables y entregables claros.",
        },
        {
            "layout": "architecture",
            "eyebrow": "08 · ARQUITECTURA",
            "title": "ARQUITECTURA LEGIBLE PARA DECISIONES DE NEGOCIO",
            "lead": "Una vista de alto nivel que explica responsabilidades, fronteras y conexiones.",
            "nodes": ["Usuario", "Frontend", "Servicios", "Datos", "Integraciones"],
            "details": [
                {"label": "EXPERIENCIA", "body": "Interfaz enfocada a la tarea y al contexto de uso."},
                {"label": "LÓGICA", "body": "Reglas de negocio centralizadas y verificables."},
                {"label": "INFORMACIÓN", "body": "Datos estructurados, permisos y trazabilidad."},
                {"label": "ECOSISTEMA", "body": "APIs y sistemas externos desacoplados."},
            ],
            "note": "DIAGRAMA EDITABLE · NODOS, LÍNEAS Y TEXTOS SON OBJETOS POWERPOINT",
        },
        {
            "layout": "workflow",
            "eyebrow": "09 · WORKFLOW",
            "title": "UN FLUJO PARA HACER VISIBLE LA AUTOMATIZACIÓN",
            "lead": "Representa entradas, validaciones, decisiones, salidas y excepciones.",
            "nodes": [
                {"index": "01", "title": "Entrada"},
                {"index": "02", "title": "Lectura"},
                {"index": "03", "title": "Validación", "decision": True},
                {"index": "04", "title": "Registro", "active": True},
                {"index": "05", "title": "Aviso"},
            ],
            "branch": {"from": 2, "label": "EXCEPCIÓN → REVISIÓN HUMANA"},
            "notes": [
                {"label": "ENTRADA", "body": "Evento que inicia el proceso."},
                {"label": "CONTROL", "body": "Reglas y validaciones explícitas."},
                {"label": "SALIDA", "body": "Resultado registrado y trazable."},
            ],
        },
        {
            "layout": "product_showcase",
            "eyebrow": "10 · CAPTURA DE PRODUCTO",
            "title": "EL PRODUCTO ES EL PROTAGONISTA",
            "lead": "Un marco sobrio para interfaces, dashboards y herramientas internas.",
            "caption": "FIG. 01 · SUSTITUIR POR CAPTURA REAL DEL PRODUCTO",
            "points": [
                {"index": "01", "title": "Tarea principal", "body": "Explica qué está resolviendo la pantalla."},
                {"index": "02", "title": "Decisión", "body": "Señala la información que guía al usuario."},
                {"index": "03", "title": "Control", "body": "Describe permisos, validación o trazabilidad."},
                {"index": "04", "title": "Resultado", "body": "Conecta la interfaz con el valor operativo."},
            ],
        },
        {
            "layout": "case_study",
            "eyebrow": "11 · CASO DE ÉXITO",
            "title": "DEL CONTEXTO AL RESULTADO, SIN ADORNOS",
            "lead": "Una estructura reutilizable para proyectos reales, identificados o anonimizados.",
            "context": "Describe el tipo de organización, el proceso y la situación de partida.",
            "problem": "Explica la fricción concreta, sus causas y a quién afectaba.",
            "solution": "Resume qué se construyó, cómo se dividió y qué decisiones fueron clave.",
            "result": "Formula un cambio observable sin inventar cifras ni atribuir resultados no medidos.",
            "technology": ["Next.js", "TypeScript", "PostgreSQL", "Vercel"],
        },
        {
            "layout": "scope_split",
            "eyebrow": "12 · ALCANCE",
            "title": "QUÉ ENTRA. QUÉ NO ENTRA. SIN AMBIGÜEDAD.",
            "lead": "Las exclusiones reciben el mismo peso visual que los entregables.",
            "included": {"label": "INCLUIDO", "title": "COMPROMISO DE ENTREGA", "items": ["Análisis y definición funcional", "Diseño de experiencia", "Desarrollo del alcance acordado", "Pruebas y despliegue", "Documentación de uso"]},
            "excluded": {"label": "NO INCLUIDO", "title": "FUERA DE ESTA FASE", "items": ["Funcionalidades no descritas", "Licencias de terceros", "Migraciones no inventariadas", "Soporte evolutivo indefinido", "Cambios regulatorios futuros"]},
        },
        {
            "layout": "phases",
            "eyebrow": "13 · FASES DEL PROYECTO",
            "title": "CADA FASE TERMINA EN ALGO UTILIZABLE",
            "lead": "Objetivo, entregable y duración se leen sin cambiar de contexto.",
            "phases": [
                {"index": "01", "title": "Análisis", "objective": "Alinear problema", "deliverable": "Mapa y alcance", "duration": "1–2 semanas"},
                {"index": "02", "title": "MVP", "objective": "Resolver el núcleo", "deliverable": "Versión operativa", "duration": "4–6 semanas", "active": True},
                {"index": "03", "title": "Validación", "objective": "Probar en contexto", "deliverable": "Ajustes priorizados", "duration": "2 semanas"},
                {"index": "04", "title": "Producción", "objective": "Lanzar y transferir", "deliverable": "Sistema desplegado", "duration": "1–2 semanas"},
            ],
        },
        {
            "layout": "roadmap",
            "eyebrow": "14 · ROADMAP",
            "title": "VISIÓN TEMPORAL SIN FALSA PRECISIÓN",
            "lead": "El calendario comunica secuencia, solapes, hitos y releases.",
            "periods": ["SEP", "OCT", "NOV", "DIC"],
            "tracks": [
                {"label": "Descubrimiento", "start": 0, "span": 1, "output": "ALCANCE"},
                {"label": "Producto", "start": 0, "span": 3, "output": "ITERACIONES", "active": True},
                {"label": "Integraciones", "start": 1, "span": 2, "output": "CONEXIONES"},
                {"label": "Lanzamiento", "start": 3, "span": 1, "output": "RELEASE"},
            ],
        },
        {
            "layout": "table",
            "eyebrow": "15 · TABLA",
            "title": "DATOS DENSOS, PERO FÁCILES DE RECORRER",
            "lead": "Un sistema sin bordes pesados para comparar alcance, estado y decisión.",
            "headers": ["BLOQUE", "DESCRIPCIÓN", "ESTADO", "DECISIÓN"],
            "widths": [1.55, 6.24, 1.55, 2.55],
            "rows": [
                ["01", "Definición funcional y prioridades", "Validado", "Continuar"],
                ["02", "Flujo principal de usuario", "En curso", "Revisar"],
                ["03", "Integración con sistema externo", "Pendiente", "Confirmar API"],
                ["04", "Despliegue y monitorización", "Previsto", "Planificar"],
                ["05", "Soporte evolutivo", "Opcional", "Decidir tras uso"],
            ],
            "highlighted_rows": [1],
            "note": "CABECERAS MONO · JERARQUÍA POR PESO Y COLOR · SIN ESTILO DE TABLA GENÉRICO",
        },
        {
            "layout": "budget",
            "eyebrow": "16 · PRESUPUESTO",
            "title": "INVERSIÓN CLARA, VINCULADA AL ALCANCE",
            "lead": "Ejemplo estructural: sustituir importes y condiciones para cada propuesta.",
            "items": [
                {"phase": "Fase 01", "scope": "Análisis y definición", "amount": "X.XXX €", "payment": "A la aceptación"},
                {"phase": "Fase 02", "scope": "Diseño y construcción", "amount": "XX.XXX €", "payment": "Por hitos"},
                {"phase": "Fase 03", "scope": "Lanzamiento", "amount": "X.XXX €", "payment": "A la entrega"},
                {"phase": "Opcional", "scope": "Evolución y soporte", "amount": "XXX €/mes", "payment": "Mensual"},
            ],
            "total": "XX.XXX €",
            "tax_note": "IMPORTES DE EJEMPLO · SUSTITUIR ANTES DE ENVIAR · IMPUESTOS NO INCLUIDOS",
        },
        {
            "layout": "conditions",
            "eyebrow": "17 · CONDICIONES",
            "title": "LAS REGLAS DEL PROYECTO TAMBIÉN SE DISEÑAN",
            "lead": "Agrupa las condiciones clave para que puedan leerse y discutirse.",
            "items": [
                {"index": "01", "label": "Validez", "value": "Periodo durante el que se mantienen alcance e inversión."},
                {"index": "02", "label": "Pagos", "value": "Calendario, hitos, vencimientos e impuestos aplicables."},
                {"index": "03", "label": "Propiedad", "value": "Código, contenidos, licencias y activos entregables."},
                {"index": "04", "label": "Cambios", "value": "Cómo se evalúa y aprueba una variación de alcance."},
                {"index": "05", "label": "Soporte", "value": "Cobertura posterior al lanzamiento y tiempos acordados."},
                {"index": "06", "label": "Terceros", "value": "Servicios, licencias y dependencias fuera del control directo."},
            ],
        },
        {
            "layout": "team",
            "eyebrow": "18 · EQUIPO",
            "title": "ROLES CLAROS, SIN DEPENDER DE FOTOGRAFÍAS",
            "lead": "La composición funciona con personas concretas o con el equipo previsto por función.",
            "people": [
                {"initials": "PD", "role": "Product direction", "focus": "Problema, prioridad, alcance y relación con negocio.", "dedication": "TRANSVERSAL"},
                {"initials": "UX", "role": "Diseño de producto", "focus": "Flujos, prototipo y experiencia de uso.", "dedication": "FASES 01–03"},
                {"initials": "EN", "role": "Engineering", "focus": "Arquitectura, desarrollo, calidad y despliegue.", "dedication": "FASES 02–04"},
                {"initials": "DA", "role": "Datos e IA", "focus": "Información, modelos, automatización y evaluación.", "dedication": "SEGÚN ALCANCE"},
            ],
        },
        {
            "layout": "stack",
            "eyebrow": "19 · STACK TECNOLÓGICO",
            "title": "TECNOLOGÍA EXPLICADA COMO SISTEMA",
            "lead": "Agrupa por responsabilidad y evita una nube indiscriminada de logos.",
            "groups": [
                {"label": "INTERFAZ", "items": ["Next.js", "React", "TypeScript"]},
                {"label": "DATOS", "items": ["PostgreSQL", "Supabase"]},
                {"label": "AUTOMATIZACIÓN", "items": ["Node.js", "APIs", "Webhooks"]},
                {"label": "IA APLICADA", "items": ["LLMs", "RAG", "OCR"]},
                {"label": "OPERACIÓN", "items": ["Vercel", "CI/CD", "Observabilidad"]},
            ],
        },
        {
            "layout": "next_steps",
            "eyebrow": "20 · PRÓXIMOS PASOS",
            "title": "UNA DECISIÓN CLARA PARA MANTENER EL IMPULSO",
            "lead": "Tres acciones concretas, ordenadas y con una referencia temporal.",
            "steps": [
                {"index": "01", "action": "Validar la propuesta", "body": "Alinear alcance, prioridades, condiciones y responsables.", "timing": "SIGUIENTE REUNIÓN"},
                {"index": "02", "action": "Celebrar el kick-off", "body": "Abrir el proyecto, confirmar accesos y cerrar el calendario.", "timing": "TRAS ACEPTACIÓN"},
                {"index": "03", "action": "Iniciar el trabajo", "body": "Empezar descubrimiento y primera entrega visible.", "timing": "SEMANA 01"},
            ],
        },
        {
            "layout": "corporate_closing",
            "eyebrow": "21 · CIERRE",
            "title": "CONSTRUIMOS EL SOFTWARE QUE VUESTRO NEGOCIO NECESITA.",
            "lead": "Tecnología a medida para convertir procesos, ideas y oportunidades en productos que funcionan.",
            "cta": "CUÉNTANOS TU PROYECTO",
            "contact": "VALENCIA · ESPAÑA",
        },
    ],
}
